<?php

namespace PORTFOLIO\Bundle\Repository;

/**
 * HobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}