# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Membre: 'bcrypt'

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # in_memory:
        #     memory: 
        #         users: 
        #             Yannis:
        #                 password: 123456
        #                 roles: 'ROLE_USER'
        
        #             admin:
        #                 password: admin
        #                 roles: 'ROLE_ADMIN'

        folio_provider:
            entity:
                class: PORTFOLIO:Bundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            http_basic: ~
            pattern: ^/
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            form_login: 
                login_path: connexion
                check_path: connexion_check
                default_target_path: accueil
            
            logout: 
                path: deconnexion
                target: accueil

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    # role_hierarchy:
    #     ROLE_ADMIN: ROLE_USER
